services:
  - type: web
    name: autoroulette-proxy
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: https://casinoscores-es.onrender.com
        sync: false
    healthCheckPath: /ping
